CREATE CACHED TABLE PUBLIC.TEST(
    ID INT NOT NULL,
    NAME VARCHAR(255)
);
CREATE CACHED TABLE PUBLIC.INDEX(
    TOKEN VARCHAR(30) SELECTIVITY 33,
    FILE VARCHAR(30) SELECTIVITY 1,
    SENTNUM INT SELECTIVITY 1,
    LINENUM INTEGER SELECTIVITY 2
);
CREATE CACHED TABLE PUBLIC.DEPINDEX(
    TOKEN VARCHAR(50) SELECTIVITY 26,
    FILE VARCHAR(30) SELECTIVITY 1,
    SENTNUM INT SELECTIVITY 1,
    LINENUM INTEGER SELECTIVITY 1
);
CREATE CACHED TABLE PUBLIC.COUNTS(
    TOKEN VARCHAR(50) SELECTIVITY 100,
    COUNT INT SELECTIVITY 5
);
CREATE CACHED TABLE PUBLIC.CONTENT(
    FILE VARCHAR(30) SELECTIVITY 4,
    SENTNUM INT SELECTIVITY 3,
    CONT VARCHAR(1000) SELECTIVITY 77,
    DEPENDENCY VARCHAR(2500) SELECTIVITY 77,
    LINENUM INTEGER SELECTIVITY 12
);

